(personal 'global)
(personal 'custom 'noerror)
(personal 'bindings)
(personal 'hl-line)
(personal 'ido)
(personal 'mac)
(personal 'recentf)
(personal 'utf-8)

(vendor 'color-theme)
(vendor 'magit 'magit-status)
(vendor 'git-commit)
